name: Docker DevOps CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  build-test:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Dependencies
      working-directory: ./app
      run: npm install

    - name: Check JavaScript Syntax
      working-directory: ./app
      run: node --check server.js

    - name: Build Docker Image
      run: docker build -t dockerlab-app ./app

    - name: Show Docker Images
      run: docker images

    - name: Pipeline Success
      run: echo "CI Pipeline Finished Successfully"

  deploy:

    needs: build-test

    if: github.event_name == 'push'

    runs-on: ubuntu-latest

    steps:

    - name: Deploy to Ubuntu Server
      uses: appleboy/ssh-action@v1.2.0

      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}

        script: |
          cd ~/docker-devops-praktikum
          git pull origin main
          docker compose down
          docker compose up -d --build