name: Docker CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build -t dockerlab-app ./app
        
      - name: Test
        run: |
          echo "Running tests..."
          test -f app/server_error.js

      - name: Show Docker Images
        run: docker images